### ISSUE TITLE
Npm test broken on fresh laptop

### ISSUE THREAD

**Issue by MrBaptastic** [iflix-letsplay/rukus#12]
Wanted to check Rukus to give me a better idea of the env, brand new laptop, I tried to run npm test and I got :

```
module.js:474
    throw err;
    ^

Error: Cannot find module 'babel/register'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /Users/mrbaptastic/bonjourlemonde/node_modules/mocha/bin/_mocha:336:3
    at Array.forEach (native)
    at Object.<anonymous> (/Users/mrbaptastic/bonjourlemonde/node_modules/mocha/bin/_mocha:328:19)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
npm ERR! Test failed.  See above for more details.
```

Pretty straightforward, missing dependency, easy fix.

**Comment by SomeoneWeird** [comment]
Great, should be simple to fix.
